[package]
name = "indent-s-expr"
version = "1.0.0"
edition = "2021"
description = "Dumb-as-rocks S-expression indenter"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dev-dependencies]
insta = "1.35.1"
rstest = "0.18.2"
rstest_reuse = "0.6.0"
